'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.1434
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("CynicsAccounting.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to /****** Object:  Database [{CSAccountDB1}]    Script Date: 03/13/2007 12:09:33 ******/
        '''CREATE DATABASE [{CSAccountDB1}] ON  PRIMARY 
        '''( NAME = N&apos;{CSAccountDB1}&apos;, FILENAME = N&apos;C:\CynicsDB\{CSAccountDB1}.mdf&apos; , SIZE = 3840KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
        ''' LOG ON 
        '''( NAME = N&apos;{CSAccountDB1}_log&apos;, FILENAME = N&apos;C:\CynicsDB\{CSAccountDB1}_log.ldf&apos; , SIZE = 768KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
        ''' COLLATE SQL_Latin1_General_CP1_CI_AS
        '''GO
        '''EXEC dbo.sp_dbcmptlevel @dbname=N&apos;{CSAccountDB1}&apos;, @n [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property CreateDB() As String
            Get
                Return ResourceManager.GetString("CreateDB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to USE [{CSAccountDB1}]
        '''--
        '''-- Definition for table MST_ACCOUNT : 
        '''--
        '''
        '''CREATE TABLE [dbo].[MST_ACCOUNT] (
        '''  [ACC_CODE]varchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
        '''  [ACC_NAME]varchar(75) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
        '''  [ACC_TYPE]tinyint NULL,
        '''  [RETAINED_EARNINGS]bit NULL,
        '''  [IS_ACTIVE]bit NULL
        ''')
        '''ON [PRIMARY]
        '''GO
        '''
        '''--
        '''-- Definition for table MST_ACCREPORT : 
        '''--
        '''
        '''CREATE TABLE [dbo].[MST_ACCREPORT] (
        '''  [ACCRPTNO]int NOT NULL,
        '''  [ACCRPT_NAME]varchar(50) COLLATE SQL_Lat [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property CreateTableProc() As String
            Get
                Return ResourceManager.GetString("CreateTableProc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 
        '''
        '''INSERT INTO [dbo].[MST_ACCOUNT] ([ACC_CODE], [ACC_NAME], [ACC_TYPE], [RETAINED_EARNINGS], [IS_ACTIVE])
        '''VALUES 
        '''  (&apos;11100&apos;, &apos;Cash On Hand&apos;, 2, 0, 1)
        '''GO
        '''
        '''INSERT INTO [dbo].[MST_ACCOUNT] ([ACC_CODE], [ACC_NAME], [ACC_TYPE], [RETAINED_EARNINGS], [IS_ACTIVE])
        '''VALUES 
        '''  (&apos;11200&apos;, &apos;Petty Cash&apos;, 2, 0, 1)
        '''GO
        '''
        '''INSERT INTO [dbo].[MST_ACCOUNT] ([ACC_CODE], [ACC_NAME], [ACC_TYPE], [RETAINED_EARNINGS], [IS_ACTIVE])
        '''VALUES 
        '''  (&apos;11310&apos;, &apos;Bank - Public Bank&apos;, 2, 0, 1)
        '''GO
        '''
        '''INSERT INTO [dbo].[MST_ACCOUNT] ( [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property CSAccountDBData() As String
            Get
                Return ResourceManager.GetString("CSAccountDBData", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to -- SYS_RPTTYPE  
        '''
        '''USE [{CSAccountDB1}]
        '''
        '''INSERT INTO [dbo].[SYS_RPTTYPE] ([RPTTYPE_CODE], [RPTTYPE_NAME], [REVERSE_VALUE])
        '''VALUES 
        '''  (&apos;DETAIL&apos;, &apos;Detail&apos;, 0)
        '''GO
        '''
        '''INSERT INTO [dbo].[SYS_RPTTYPE] ([RPTTYPE_CODE], [RPTTYPE_NAME], [REVERSE_VALUE])
        '''VALUES 
        '''  (&apos;DETAILR&apos;, &apos;Detail With Reverse Value&apos;, 1)
        '''GO
        '''
        '''INSERT INTO [dbo].[SYS_RPTTYPE] ([RPTTYPE_CODE], [RPTTYPE_NAME], [REVERSE_VALUE])
        '''VALUES 
        '''  (&apos;HEADING&apos;, &apos;Heading&apos;, 0)
        '''GO
        '''
        '''INSERT INTO [dbo].[SYS_RPTTYPE] ([RPTTYPE_CODE], [RPTTYPE_NAME], [REVER [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property CSAccountDBSystemData() As String
            Get
                Return ResourceManager.GetString("CSAccountDBSystemData", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to IF  EXISTS (SELECT name FROM sys.databases WHERE name = N&apos;{CSAccountDB1}&apos;)
        '''DROP DATABASE [{CSAccountDB1}].
        '''</summary>
        Friend ReadOnly Property DropDB() As String
            Get
                Return ResourceManager.GetString("DropDB", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property logo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
